php_version: 8.4.10
environment:
    DATABASE_URL: "mysql://app:app@127.0.0.1:3323/kaiser01?serverVersion=10.6.16-MariaDB-1:10.6.16+maria~ubu2004&charset=utf8"
    DATABASE_USER: "app"
    DATABASE_USERNAME: "app"
    DATABASE_PASSWORD: "app"